# LC transmission line parameters
# Values extracted from technical sheet (see sources)
# Power rule scaling for AC resistance induced from experimental data
# Model used: R_AC = R_DC (1 + k * f ** power_rule)

L:  # Inductance for all inductors
    value: 0.00033   # H
    tolerance: 0.000066    # H

C:  # Capacitance for capacitors 1-39
    value: 0.000000015    # F
    tolerance: 0.0000000015   # F

C_end:  # Total apacitance for capacitors 0 & 40
    value: 0.0000000075   # F
    tolerance: 0.00000000075  # F

R_in:  # Resistance for initial resistor and oscilloscope
    value: 150  # Ohm
    tolerance: 7.5  # Ohm

R_out:  # Resistance for variable termination resistor when fixed
    value: 148  # Ohm
    tolerance: 0.05 # 5%

R_L:    # DC internal resistance for all inductors
    value: 0.730  # Ohm
    tolerance: 0.0730  # Ohm

f_test: # Test frequency for quality factor
    value: 796000   # Hz
    tolerance: 1000  # Hz

Q_test: # Quality factor at test frequenct f_test
    value: 65
    tolerance: 1

R_L_test: # Inductor resistance at test frequency f_test
    value: 25.391801792152826  # Ohm

N:  # Number of nodes in the system (includes node 0)
    value: 41

power_rule: # Power scaling with frequency of R_L
    value: 0
    tolerance: 0